version: '3'

networks:
  laravel:

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: letsmeet_nginx
    ports:
      - 8081:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
      - sql
    networks:
      - laravel

 sql:
   image: microsoft/mssql-server-linux:latest
   container_name: timetrax_sql
   restart: unless-stopped
   tty: true
   ports:
     - "14332:1433"
   environment:
     SA_PASSWORD: "secret"
     ACCEPT_EULA: "Y"
   volumes:
     - ./mssql:/var/opt/mssql
   networks:
     - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: letsmeet_php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: letsmeet_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: letsmeet_npm
    volumes:
      - ./src:/var/www/html
    # ports:
    #   - 3000:3000
    #   - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: letsmeet_artisan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - sql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel

  supervisor:
    build:
      context: .
      dockerfile: supervisor.dockerfile
    container_name: letsmeet_supervisor
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - artisan
    networks:
      - laravel

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   container_name: mailhog
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  #   networks:
  #     - laravel
