version: '3'

services:
  php:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:stable-alpine
    expose:
      - 80
    environment:
      - VIRTUAL_HOST= myapp.test
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

  npm:
    image: node:latest
    user: node
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: run watch
    entrypoint: [ 'npm' ]

  supervisor:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - ./:/var/www/html
    entrypoint: ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]
    depends_on:
      - php


volumes:
  mysqldata:

networks:
  default:
    external:
      name: reverse-proxy
