version: '3'

services:
  php:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - sql

  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

  sql:
    image: microsoft/mssql-server-linux:latest
    restart: unless-stopped
    tty: true
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${DB_PASSWORD_TA}"
      ACCEPT_EULA: "Y"
    volumes:
      - mssqldata:/var/opt/mssql

#  npm:
#    image: node:13.7
#    user: node
#    volumes:
#      - ./:/assets
#    working_dir: /assets
#    command: run watch
#    entrypoint: [ 'npm' ]

volumes:
  mysqldata:
  mssqldata:
